services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=12345'
    volumes:
      - '~/volumes/aqurumedia/postgres:/var/lib/postgresql/data'

